---

"COURSE": "CAU_DRALG_2025"
"ASSIGNMENT": "ASSIGNMENT_05"

"ID": "20001234"
"FILES":
    - "**your-path-to-directory**/cau-dralg-2025/assignment_05/sort.py" 
"PROBLEMS": 
    - "PROBLEM_01"
    - "PROBLEM_02"
    - "PROBLEM_03"
    - "PROBLEM_04"
