---

"COURSE": "CAU_DRALG_2025"
"ASSIGNMENT": "ASSIGNMENT_03"

"ID": "20001234"
"FILES":
    - "**your-path-to-directory**/cau-dralg-2025/assignment_03/singlylinkedlist.py" 
"PROBLEMS": 
    - "PROBLEM_01"
    - "PROBLEM_02"
    - "PROBLEM_03"
    - "PROBLEM_04"
    - "PROBLEM_05"
    - "PROBLEM_06"
    - "PROBLEM_07"
    - "PROBLEM_08"
    - "PROBLEM_09"
    - "PROBLEM_10"
    - "PROBLEM_11"
        
