---

"COURSE": "CAU_DRALG_2025"
"ASSIGNMENT": "ASSIGNMENT_00"

"ID": "20001234"
"FILES":
    - "**your-path-to-directory**/cau-dralg-2025/assignment_00/main.py"    
"PROBLEMS": 
    - "PROBLEM_01"
    